from django.urls import path
from .views import *

urlpatterns = [
    path('register',RegisterView.as_view(),name = 'register'),
    path('login',Login.as_view(),name = 'login'),
    path('logout',Logout.as_view(),name = 'logout'),
    path('create/profile',CreateProfile.as_view(),name = 'cr_profile'),
    path('myprofile/<int:pk>',ProfileDetail.as_view(),name = 'myprofile'),
    path('cr/cat',CategoryCreate.as_view(),name = 'cr_cat'),
    path('cats',CategoryList.as_view(),name = 'cats'),
    path('cr/prod',ProductCreate.as_view(),name = 'cr_prod'),
    path('products',ProductList.as_view(),name = 'products'),
    path('product/<int:pk>',ProductDetail.as_view(),name = 'product'),
    path('add/image',ImageCreate.as_view(),name = 'cr_image'),
    path('images/<int:pk>', ImageList.as_view(), name='images_pr'),
    path('product/<int:pk>/add-cart', AddToCart.as_view(), name='add_cart'),
    path('cart', CartList.as_view(), name='cart'),
    path('orders', OrderList.as_view(), name='orders'), 
    path('order/<int:pk>', OrderDetail.as_view(), name='order_detail'),
    path('order/create', OrderView.as_view(), name='order_create'),
    path('cart/delete/<int:pk>', DeleteCartItem.as_view(), name='cart_delete'),
    path('cart/change/<int:pk>/',ChangeCartQuantity.as_view(),name='cart_change'),
    path('product/delete/<int:pk>/', DeleteProduct.as_view(), name='delete_product'),
    path('category/<int:pk>/', CategoryProducts.as_view(), name='category_products'),
    path('',Home.as_view(),name = 'home'),
    path('favorite/add/<int:pk>',AddFavorite.as_view(),name='favorite_add'),
    path('my/products', MyProducts.as_view(), name='my_products'),
    path('my/favorites', MyFavorites.as_view(), name='my_favorites'),
    path('favorite/remove/<int:pk>/',RemoveFavorite.as_view(),name='favorite_remove'),
    path('product/edit/<int:pk>/', ProductEdit.as_view(), name='product_edit'),
    path('profile/edit/<int:pk>/', ProfileEdit.as_view(), name='profile_edit'),
    path('admin1', AdminDashboard.as_view(), name='admin_dashboard'),
    path('admin1/users', AdminUsers.as_view(), name='admin_users'),
    path('admin1/users/<int:pk>',AdminUserDetail.as_view(),name='admin_user_detail'),
    path('admin1/categories/',AdminCategories.as_view(),name='admin_categories'),
    path('admin1/products/',AdminProducts.as_view(),name='admin_products'),
    path('admin1/orders/',AdminOrders.as_view(),name='admin_orders'),
    path('admin1/orders/<int:pk>/',AdminOrderDetail.as_view(),name='admin_order_detail'),
    path('admin1/categories/add/',AdminCategoryCreate.as_view(),name='admin_category_create'),
    path('admin1/categories/<int:pk>/edit/',AdminCategoryEdit.as_view(),name='admin_category_edit'),
    path('admin1/categories/<int:pk>/delete/',AdminCategoryDelete.as_view(),name='admin_category_delete'),
    path('admin1/users/<int:pk>/delete/',AdminUserDelete.as_view(),name='admin_user_delete'),
    path('admin1/products/<int:pk>/delete/',AdminProductDelete.as_view(),name='admin_product_delete'),
    path('ai/', AIView.as_view(), name='ai'),
]